### ISSUE TITLE
[Request] Ability to enter colour by numeric value

### ISSUE THREAD

**Issue by Taomyn** [pascalfree/calendar-color#2]
Would it be possible in a future version to be able to enter the colour value using a hex/decimal value? Makes it easier to enter the colour from another source. Thanks.

**Comment by pascalfree** [comment]
Thanks for your suggestion and sorry for not replying to it sooner.

In the new version 0.3 it is now possible to enter a color in the hex format like #rrggbb.
Currently the entered color value will lose some accuracy due to https://github.com/LarsWerkman/HoloColorPicker/issues/31. I'll fix that in the next version.
v0.3 will soon be available in f-droid.
